"""
backend/app/domain/enums.py
Controlled vocabularies. No free-text status fields anywhere in the core engine.
"""
from enum import Enum


class DecisionOutcome(str, Enum):
    BLOCK = "BLOCK"
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"


class ReplayabilityStatus(str, Enum):
    REPLAYABLE = "REPLAYABLE"
    PARTIALLY_REPLAYABLE = "PARTIALLY_REPLAYABLE"
    NON_REPLAYABLE = "NON_REPLAYABLE"


class NonReplayableReason(str, Enum):
    MISSING_INPUT = "MISSING_INPUT"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    MISSING_MODEL_VERSION = "MISSING_MODEL_VERSION"
    MISSING_POLICY_VERSION = "MISSING_POLICY_VERSION"
    NON_DETERMINISTIC_TOOL = "NON_DETERMINISTIC_TOOL"
    EXTERNAL_STATE_CHANGED = "EXTERNAL_STATE_CHANGED"
    PROVENANCE_GAP = "PROVENANCE_GAP"
    UNKNOWN_DEPENDENCY = "UNKNOWN_DEPENDENCY"


class MutationType(str, Enum):
    REMOVE_EVIDENCE = "REMOVE_EVIDENCE"
    ADD_EVIDENCE = "ADD_EVIDENCE"
    MODIFY_EVIDENCE = "MODIFY_EVIDENCE"
    CHANGE_POLICY = "CHANGE_POLICY"
    CHANGE_MODEL = "CHANGE_MODEL"
    CHANGE_THRESHOLD = "CHANGE_THRESHOLD"
    REMOVE_TOOL_RESULT = "REMOVE_TOOL_RESULT"
    MODIFY_TOOL_RESULT = "MODIFY_TOOL_RESULT"
    CHANGE_INPUT = "CHANGE_INPUT"
    DISABLE_CONTROL = "DISABLE_CONTROL"


class CausalStatus(str, Enum):
    DECISION_CRITICAL = "DECISION_CRITICAL"
    DECISION_IRRELEVANT = "DECISION_IRRELEVANT"
    CONTRIBUTORY = "CONTRIBUTORY"
    NON_DETERMINATIVE = "NON_DETERMINATIVE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NON_REPLAYABLE = "NON_REPLAYABLE"


class GovernanceStatus(str, Enum):
    SATISFIED = "SATISFIED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EvidenceClassification(str, Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    SENSITIVE = "SENSITIVE"
    RESTRICTED = "RESTRICTED"
