/**
 * staticApi.ts
 *
 * Drop-in replacement for liveApi that runs entirely client-side against a
 * precomputed bundle (frontend/public/data/bundle.json, generated by
 * backend/scripts/dump_static_bundle.py from the SAME engines the live API
 * uses). Every list/detail/lineage/risk/governance call below is a lookup
 * into that frozen bundle. The one call that has to compute something new --
 * counterfactual() -- runs staticEngine.ts, a faithful TS port of the
 * backend's decision/mutation/diff/causal engines, so mutations you build in
 * the Replay Lab are genuinely evaluated, not looked up. See STATUS.md for
 * why this exists: GitHub Pages can't run the Python backend.
 */
import type { DecisionSummary, DecisionDetail, LineageGraph, CounterfactualOut, RiskAssessment, GovernanceFinding } from "./liveApi";
import { runCounterfactual } from "./staticEngine";
import type { StaticContext } from "./staticEngine";

interface Bundle {
  decisions: DecisionSummary[];
  details: Record<string, DecisionDetail>;
  lineage: Record<string, LineageGraph>;
  risk: Record<string, RiskAssessment>;
  governance: Record<string, GovernanceFinding[]>;
  contexts: Record<string, StaticContext>;
}

let bundlePromise: Promise<Bundle> | null = null;

function loadBundle(): Promise<Bundle> {
  if (!bundlePromise) {
    const base = (import.meta as any).env?.BASE_URL || "/";
    bundlePromise = fetch(`${base}data/bundle.json`.replace(/\/\//g, "/")).then((res) => {
      if (!res.ok) throw new Error(`Could not load static demo data (${res.status})`);
      return res.json();
    });
  }
  return bundlePromise;
}

function notAvailable(what: string): never {
  throw new Error(`${what} is not available in the static demo build. Run the backend locally for this feature (see README).`);
}

export const staticApi = {
  listDecisions: async () => (await loadBundle()).decisions,

  getDecision: async (id: string) => {
    const b = await loadBundle();
    const d = b.details[id];
    if (!d) throw new Error(`Decision ${id} not found`);
    return d;
  },

  getLineage: async (id: string) => {
    const b = await loadBundle();
    const g = b.lineage[id];
    if (!g) throw new Error(`Lineage for ${id} not found`);
    return g;
  },

  replay: async (id: string) => {
    const b = await loadBundle();
    const ctx = b.contexts[id];
    if (!ctx) throw new Error(`Decision ${id} not found`);
    const detail = b.details[id];
    return {
      replay_id: `static-replay-${id}`,
      outcome: detail.final_outcome,
      score: detail.risk_score,
      replayability_status: detail.replayability_status,
    };
  },

  counterfactual: async (
    id: string,
    mutations: { type: string; target: string; reason: string; payload?: Record<string, unknown> }[]
  ): Promise<CounterfactualOut> => {
    const b = await loadBundle();
    const ctx = b.contexts[id];
    if (!ctx) throw new Error(`Decision ${id} not found`);
    const result = runCounterfactual(ctx, mutations);
    return {
      counterfactual_id: `static-cf-${id}-${Date.now()}`,
      decision_id: id,
      original_outcome: result.original_outcome,
      original_score: result.original_score,
      counterfactual_outcome: result.counterfactual_outcome,
      counterfactual_score: result.counterfactual_score,
      diverged: result.diverged,
      score_delta: result.score_delta,
      causal_status: result.causal_status,
      causal_explanation: result.causal_explanation,
      is_multi_variable: result.is_multi_variable,
      diff_fields: result.diff_fields,
    };
  },

  getRisk: async (id: string) => {
    const b = await loadBundle();
    const r = b.risk[id];
    if (!r) throw new Error(`Risk assessment for ${id} not found`);
    return r;
  },

  getGovernance: async (id: string) => {
    const b = await loadBundle();
    const g = b.governance[id];
    if (!g) throw new Error(`Governance findings for ${id} not found`);
    return g;
  },

  getEvents: async (_id: string) => notAvailable("Event history"),
  getIncident: async (_id: string) => notAvailable("Incident detail"),
  getIncidentTimeline: async (_id: string) => notAvailable("Incident timeline"),
  getIncidentBlastRadius: async (_id: string) => notAvailable("Blast radius"),
  policyImpactReplay: async (_policyId: string, _body: any) => notAvailable("Policy impact replay"),

  health: async () => ({ status: "ok (static demo, no backend)" }),
};
